Q1. Create a model that predicts crop yeilds for apples (target variable) by looking at the average temperature, rainfall and humidity (input variables or features) in different regions.

In [1]:
import numpy as np
import torch

# input

inputs_p = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')

# target

targets_p = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

In [2]:
t_targets=torch.from_numpy(targets_p)
print(t_targets)
t_inputs=torch.from_numpy(inputs_p)
print(t_inputs)

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])
tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])


In [3]:
w = torch.randn(1, 3, requires_grad=True)
b = torch.randn(5, requires_grad=True)
print(w)
print(b)

tensor([[0.1654, 0.8475, 0.3279]], requires_grad=True)
tensor([ 0.6932, -0.0900, -0.1867,  0.4290, -0.0159], requires_grad=True)


In [4]:
def model(X):
    return X @ w.t() + b

# Generating prediction and compare with targets

k=0
for x in t_inputs:
    preds = model(x)
    print("Prediction is :n",preds)
    print("Target is :g",t_targets[k])
    k+=1

Prediction is :n tensor([83.6470, 82.8638, 82.7671, 83.3828, 82.9379], grad_fn=<AddBackward0>)
Target is :g tensor([56.])
Prediction is :n tensor([111.3066, 110.5234, 110.4267, 111.0424, 110.5975],
       grad_fn=<AddBackward0>)
Target is :g tensor([81.])
Prediction is :n tensor([147.6637, 146.8806, 146.7838, 147.3995, 146.9547],
       grad_fn=<AddBackward0>)
Target is :g tensor([119.])
Prediction is :n tensor([66.1353, 65.3521, 65.2554, 65.8711, 65.4262], grad_fn=<AddBackward0>)
Target is :g tensor([22.])
Prediction is :n tensor([116.4156, 115.6325, 115.5357, 116.1514, 115.7066],
       grad_fn=<AddBackward0>)
Target is :g tensor([103.])


In [5]:
def mse_loss(predictions, targets):
    difference = predictions - targets
    return torch.sum(difference * difference)/ difference.numel()

# compute loss

k=0
for x in t_inputs:
    preds = model(x)
    print("Prediction is :n",preds)
    print("Target is :g",t_targets[k])
    print("Loss is: ",mse_loss(preds,t_targets[k]))
    k+=1

Prediction is :n tensor([83.6470, 82.8638, 82.7671, 83.3828, 82.9379], grad_fn=<AddBackward0>)
Target is :g tensor([56.])
Loss is:  tensor(735.5933, grad_fn=<DivBackward0>)
Prediction is :n tensor([111.3066, 110.5234, 110.4267, 111.0424, 110.5975],
       grad_fn=<AddBackward0>)
Target is :g tensor([81.])
Loss is:  tensor(886.9210, grad_fn=<DivBackward0>)
Prediction is :n tensor([147.6637, 146.8806, 146.7838, 147.3995, 146.9547],
       grad_fn=<AddBackward0>)
Target is :g tensor([119.])
Loss is:  tensor(791.7747, grad_fn=<DivBackward0>)
Prediction is :n tensor([66.1353, 65.3521, 65.2554, 65.8711, 65.4262], grad_fn=<AddBackward0>)
Target is :g tensor([22.])
Loss is:  tensor(1901.7731, grad_fn=<DivBackward0>)
Prediction is :n tensor([116.4156, 115.6325, 115.5357, 116.1514, 115.7066],
       grad_fn=<AddBackward0>)
Target is :g tensor([103.])
Loss is:  tensor(166.2234, grad_fn=<DivBackward0>)


In [6]:
# Computing gradient and print calculated loss 

k=0
for x in t_inputs:
      # Generate Prediction
      preds = model(x)
      loss = mse_loss(preds, t_targets[k])
      k+=1
      loss.backward()
      with torch.no_grad():
          w -= w.grad *1e-6
          b -= b.grad * 1e-6
          w.grad.zero_()
          b.grad.zero_()
print("Loss",loss)

Loss tensor(75.3467, grad_fn=<DivBackward0>)


In [7]:
epochs = 100
for i in range(epochs):
    k=0
    for x in t_inputs:
        # Generate Prediction
        preds = model(x)
        loss = mse_loss(preds, t_targets[k])
        k+=1
        loss.backward()
        with torch.no_grad():
            w -= w.grad *1e-6
            b -= b.grad * 1e-6
            w.grad.zero_()
            b.grad.zero_()
    print(f"Epoch {i}/{epochs}: Loss: {loss}")

Epoch 0/100: Loss: 22.687429428100586
Epoch 1/100: Loss: 2.343179225921631
Epoch 2/100: Loss: 1.5823783874511719
Epoch 3/100: Loss: 12.056448936462402
Epoch 4/100: Loss: 28.375234603881836
Epoch 5/100: Loss: 47.13175964355469
Epoch 6/100: Loss: 66.23885345458984
Epoch 7/100: Loss: 84.47754669189453
Epoch 8/100: Loss: 101.19169616699219
Epoch 9/100: Loss: 116.08455657958984
Epoch 10/100: Loss: 129.0798797607422
Epoch 11/100: Loss: 140.23410034179688
Epoch 12/100: Loss: 149.67613220214844
Epoch 13/100: Loss: 157.5697479248047
Epoch 14/100: Loss: 164.0912628173828
Epoch 15/100: Loss: 169.41329956054688
Epoch 16/100: Loss: 173.6992645263672
Epoch 17/100: Loss: 177.0972900390625
Epoch 18/100: Loss: 179.73983764648438
Epoch 19/100: Loss: 181.7430877685547
Epoch 20/100: Loss: 183.2073974609375
Epoch 21/100: Loss: 184.22021484375
Epoch 22/100: Loss: 184.8548126220703
Epoch 23/100: Loss: 185.17437744140625
Epoch 24/100: Loss: 185.23220825195312
Epoch 25/100: Loss: 185.0730438232422
Epoch 26/100

In [8]:
k=0
for x in t_inputs:
    preds = model(x)
    print("Prediction is :n",preds)
    print("Target is :g",t_targets[k])
    k+=1

Prediction is :n tensor([60.0392, 59.2563, 59.1595, 59.7751, 59.3303], grad_fn=<AddBackward0>)
Target is :g tensor([56.])
Prediction is :n tensor([81.5367, 80.7537, 80.6570, 81.2726, 80.8278], grad_fn=<AddBackward0>)
Target is :g tensor([81.])
Prediction is :n tensor([118.8714, 118.0884, 117.9916, 118.6072, 118.1625],
       grad_fn=<AddBackward0>)
Target is :g tensor([119.])
Prediction is :n tensor([34.2525, 33.4695, 33.3728, 33.9883, 33.5436], grad_fn=<AddBackward0>)
Target is :g tensor([22.])
Prediction is :n tensor([92.9679, 92.1850, 92.0882, 92.7038, 92.2590], grad_fn=<AddBackward0>)
Target is :g tensor([103.])
