1) Create a Numpy array of size 4 x 5.

In [3]:
import numpy as np
matrix=np.array([[1,2,3,4],[4,5,6,4],[7,8,9,4],[10,11,12,4],[13,14,15,4]])
print(matrix)

[[ 1  2  3  4]
 [ 4  5  6  4]
 [ 7  8  9  4]
 [10 11 12  4]
 [13 14 15  4]]


2) Randomly initialize the array.

In [10]:
rand=np.random.rand(5)
print(rand)

[0.46608324 0.3144786  0.21682321 0.62409528 0.67806998]


3) Get the Transpose of the Matrix that you created. Create a square matrix and find its determinant.

In [11]:
print(matrix.transpose())

[[ 1  4  7 10 13]
 [ 2  5  8 11 14]
 [ 3  6  9 12 15]
 [ 4  4  4  4  4]]


4) Create another matrix of size 5 x 4 and randomly initialize it.

In [12]:
rand=np.random.rand(5,4)
print(rand)

[[0.89050012 0.15440471 0.78508522 0.46574174]
 [0.49422221 0.78480468 0.28309528 0.73176822]
 [0.99903864 0.89235322 0.58962151 0.42131003]
 [0.29716664 0.61875279 0.74221678 0.19687764]
 [0.69811749 0.62953523 0.77406645 0.60597402]]


5) Perform Matrix multiplication.
6) Perform element wise matrix multiplication.

In [15]:
matrix=np.array([[1,2],[3,4]])
matrix1=np.array([[3,4],[5,4]])*matrix
print(matrix1)
matrix1=np.dot(np.array([[3,4],[5,4]]),matrix)
print(matrix1)
matrix1=matrix1.T
print(matrix1)

[[ 3  8]
 [15 16]]
[[15 22]
 [17 26]]
[[15 17]
 [22 26]]


7) Find mean, median of the numpy array created.

In [16]:
print(np.mean(matrix1))
print(np.mean(matrix1,axis=0))
print(np.mean(matrix1,axis=1))
print(np.median(matrix1))

20.0
[18.5 21.5]
[16. 24.]
19.5


8) Obtain each row in the second column of the first array.

In [18]:
print(matrix[:,1])

[2 4]


9) Convert Numeric entries(columns) of Iris.csv to Mean Centered Version

In [ ]:
import numpy as np
from google.colab import drive
drive.mount('/content/drive')
data=pd.read_csv('/content/drive/MyDrive/Iris.csv - Iris.csv.csv')
centered=data['SepalLengthCm']-np.mean(data['SepalLengthCm'],axis=0)
print(centered)

10) Study about numpy array attributes and implement it on the first matrix.