## #Task 1: Try the algo on Dataset3 - OneHotEncoding of features:and Train test Division 85%-15%

In [1]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
import numpy as np

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [9]:
datasets = pd.read_csv('/content/drive/MyDrive/Machine_Learning_Labs/Lab3/Dataset3.csv') 
print(datasets)

#Use One Hot Encoder from scikit learn
onehotencoder = OneHotEncoder()
#reshape the 1-D country array to 2-D as fit_transform expects 2-D and finally fit the object 
x = onehotencoder.fit_transform(datasets.Outlook.values.reshape(-1,1)).toarray()
y = onehotencoder.fit_transform(datasets.Temp.values.reshape(-1,1)).toarray()
z = onehotencoder.fit_transform(datasets.Wind.values.reshape(-1,1)).toarray()
w = onehotencoder.fit_transform(datasets.Humidity.values.reshape(-1,1)).toarray()

   Outlook Temp Wind  Humidity  Class
0        R    H    F         1      0
1        R    H    T         2      0
2        O    H    F         1      1
3        R    M    F         1      1
4        S    C    F         1      1
5        O    C    T         0      0
6        O    C    T         1      1
7        R    M    F         1      0
8        O    C    F         0      1
9        S    M    F         2      1
10       R    C    T         2      0
11       O    M    T         0      1
12       O    H    F         1      1
13       S    M    T         1      0


In [27]:
#R-1,O-0,S-2
x

array([[0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [24]:
#H-1,M-0,C-2
y

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
#F-0,T-1
z

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [26]:
#0-0,1-1,2-2
w

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [10]:
dfOneHot = pd.DataFrame(x, columns = ["Outlook_"+str(int(i)) for i in range(datasets.shape[1]-2)]) 
df = pd.concat([datasets, dfOneHot], axis=1) #column
#droping the country column 
df= df.drop(['Outlook'], axis=1) 
#printing to verify 
print(df)
datasets = df

   Temp Wind  Humidity  Class  Outlook_0  Outlook_1  Outlook_2
0     H    F         1      0        0.0        1.0        0.0
1     H    T         2      0        0.0        1.0        0.0
2     H    F         1      1        1.0        0.0        0.0
3     M    F         1      1        0.0        1.0        0.0
4     C    F         1      1        0.0        0.0        1.0
5     C    T         0      0        1.0        0.0        0.0
6     C    T         1      1        1.0        0.0        0.0
7     M    F         1      0        0.0        1.0        0.0
8     C    F         0      1        1.0        0.0        0.0
9     M    F         2      1        0.0        0.0        1.0
10    C    T         2      0        0.0        1.0        0.0
11    M    T         0      1        1.0        0.0        0.0
12    H    F         1      1        1.0        0.0        0.0
13    M    T         1      0        0.0        0.0        1.0


In [11]:
dfOneHot1 = pd.DataFrame(y, columns = ["Temp_"+str(int(i)) for i in range(df.shape[1]-4)]) 
df = pd.concat([df, dfOneHot1], axis=1) #column
#droping the country column 
df= df.drop(['Temp'], axis=1) 
#printing to verify 
print(df)
datasets = df

   Wind  Humidity  Class  Outlook_0  ...  Outlook_2  Temp_0  Temp_1  Temp_2
0     F         1      0        0.0  ...        0.0     0.0     1.0     0.0
1     T         2      0        0.0  ...        0.0     0.0     1.0     0.0
2     F         1      1        1.0  ...        0.0     0.0     1.0     0.0
3     F         1      1        0.0  ...        0.0     0.0     0.0     1.0
4     F         1      1        0.0  ...        1.0     1.0     0.0     0.0
5     T         0      0        1.0  ...        0.0     1.0     0.0     0.0
6     T         1      1        1.0  ...        0.0     1.0     0.0     0.0
7     F         1      0        0.0  ...        0.0     0.0     0.0     1.0
8     F         0      1        1.0  ...        0.0     1.0     0.0     0.0
9     F         2      1        0.0  ...        1.0     0.0     0.0     1.0
10    T         2      0        0.0  ...        0.0     1.0     0.0     0.0
11    T         0      1        1.0  ...        0.0     0.0     0.0     1.0
12    F     

In [12]:
dfOneHot2 = pd.DataFrame(z, columns = ["Humidity_"+str(int(i)) for i in range(df.shape[1]-7)]) 
df = pd.concat([df, dfOneHot2], axis=1) #column
#droping the country column 
df= df.drop(['Humidity'], axis=1) 
#printing to verify 
print(df)
datasets = df

   Wind  Class  Outlook_0  Outlook_1  ...  Temp_1  Temp_2  Humidity_0  Humidity_1
0     F      0        0.0        1.0  ...     1.0     0.0         1.0         0.0
1     T      0        0.0        1.0  ...     1.0     0.0         0.0         1.0
2     F      1        1.0        0.0  ...     1.0     0.0         1.0         0.0
3     F      1        0.0        1.0  ...     0.0     1.0         1.0         0.0
4     F      1        0.0        0.0  ...     0.0     0.0         1.0         0.0
5     T      0        1.0        0.0  ...     0.0     0.0         0.0         1.0
6     T      1        1.0        0.0  ...     0.0     0.0         0.0         1.0
7     F      0        0.0        1.0  ...     0.0     1.0         1.0         0.0
8     F      1        1.0        0.0  ...     0.0     0.0         1.0         0.0
9     F      1        0.0        0.0  ...     0.0     1.0         1.0         0.0
10    T      0        0.0        1.0  ...     0.0     0.0         0.0         1.0
11    T      1  

In [13]:
dfOneHot3 = pd.DataFrame(w, columns = ["Wind_"+str(int(i)) for i in range(df.shape[1]-7)]) 
df = pd.concat([df, dfOneHot3], axis=1) #column
#droping the country column 
df= df.drop(['Wind'], axis=1) 
#printing to verify 
print(df)
datasets = df

    Class  Outlook_0  Outlook_1  Outlook_2  ...  Humidity_1  Wind_0  Wind_1  Wind_2
0       0        0.0        1.0        0.0  ...         0.0     0.0     1.0     0.0
1       0        0.0        1.0        0.0  ...         1.0     0.0     0.0     1.0
2       1        1.0        0.0        0.0  ...         0.0     0.0     1.0     0.0
3       1        0.0        1.0        0.0  ...         0.0     0.0     1.0     0.0
4       1        0.0        0.0        1.0  ...         0.0     0.0     1.0     0.0
5       0        1.0        0.0        0.0  ...         1.0     1.0     0.0     0.0
6       1        1.0        0.0        0.0  ...         1.0     0.0     1.0     0.0
7       0        0.0        1.0        0.0  ...         0.0     0.0     1.0     0.0
8       1        1.0        0.0        0.0  ...         0.0     1.0     0.0     0.0
9       1        0.0        0.0        1.0  ...         0.0     0.0     0.0     1.0
10      0        0.0        1.0        0.0  ...         1.0     0.0     0.0 

In [28]:
datasets

Class  Outlook_0  Outlook_1  Outlook_2  ...  Humidity_1  Wind_0  Wind_1  Wind_2
0       0        0.0        1.0        0.0  ...         0.0     0.0     1.0     0.0
1       0        0.0        1.0        0.0  ...         1.0     0.0     0.0     1.0
2       1        1.0        0.0        0.0  ...         0.0     0.0     1.0     0.0
3       1        0.0        1.0        0.0  ...         0.0     0.0     1.0     0.0
4       1        0.0        0.0        1.0  ...         0.0     0.0     1.0     0.0
5       0        1.0        0.0        0.0  ...         1.0     1.0     0.0     0.0
6       1        1.0        0.0        0.0  ...         1.0     0.0     1.0     0.0
7       0        0.0        1.0        0.0  ...         0.0     0.0     1.0     0.0
8       1        1.0        0.0        0.0  ...         0.0     1.0     0.0     0.0
9       1        0.0        0.0        1.0  ...         0.0     0.0     0.0     1.0
10      0        0.0        1.0        0.0  ...         1.0     0.0     0.0     1.0
11      1        1.0        0.0        0.0  ...         1.0     1.0     0.0     0.0
12      1        1.0        0.0        0.0  ...         0.0     0.0     1.0     0.0
13      0        0.0        0.0        1.0  ...         1.0     0.0     1.0     0.0

[14 rows x 12 columns]

In [14]:
import seaborn as sns

corr = datasets.corr()
corr.head()


Class  Outlook_0  Outlook_1  ...    Wind_0    Wind_1    Wind_2
Class      1.000000   0.458333  -0.559431  ...  0.100504  0.125000 -0.251259
Outlook_0  0.458333   1.000000  -0.645497  ...  0.603023 -0.125000 -0.452267
Outlook_1 -0.559431  -0.645497   1.000000  ... -0.389249  0.043033  0.337350
Outlook_2  0.100504  -0.452267  -0.389249  ... -0.272727  0.100504  0.151515
Temp_0     0.043033   0.258199  -0.244444  ...  0.337350 -0.258199 -0.025950

[5 rows x 12 columns]

In [15]:
newdata = datasets.iloc[:,1:12]
newtarget = datasets.iloc[:,0:1]
print(newdata)
print(newtarget)

    Outlook_0  Outlook_1  Outlook_2  Temp_0  ...  Humidity_1  Wind_0  Wind_1  Wind_2
0         0.0        1.0        0.0     0.0  ...         0.0     0.0     1.0     0.0
1         0.0        1.0        0.0     0.0  ...         1.0     0.0     0.0     1.0
2         1.0        0.0        0.0     0.0  ...         0.0     0.0     1.0     0.0
3         0.0        1.0        0.0     0.0  ...         0.0     0.0     1.0     0.0
4         0.0        0.0        1.0     1.0  ...         0.0     0.0     1.0     0.0
5         1.0        0.0        0.0     1.0  ...         1.0     1.0     0.0     0.0
6         1.0        0.0        0.0     1.0  ...         1.0     0.0     1.0     0.0
7         0.0        1.0        0.0     0.0  ...         0.0     0.0     1.0     0.0
8         1.0        0.0        0.0     1.0  ...         0.0     1.0     0.0     0.0
9         0.0        0.0        1.0     0.0  ...         0.0     0.0     0.0     1.0
10        0.0        1.0        0.0     1.0  ...         1.0     

In [16]:
from sklearn.model_selection import train_test_split
#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(newdata,
newtarget, test_size = 0.85, random_state = 125)

In [17]:
import numpy as np
mnb = MultinomialNB()
gnb = GaussianNB()
#Train the model using the training sets
gnb.fit(data_train, target_train)
mnb.fit(data_train, target_train)
#Predict the response for test dataset
target_pred = gnb.predict(data_test)
target_pred1 = mnb.predict(data_test)

print(target_pred)
print(target_pred1)

[1 0 0 0 1 0 1 1 1 0 1 1]
[1 0 0 0 1 0 1 1 1 0 1 1]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [18]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[2, 3],
       [3, 4]])

In [19]:
predict = gnb.predict([[0,1,0,0,0,1,1,0,0,1,0]])
print(predict)
predict = mnb.predict([[0,1,0,0,0,1,1,0,0,1,0]])
print(predict)

[1]
[1]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  "X does not have valid feature names, but"


In [20]:
predict1 = gnb.predict([[0,0,1,0,0,1,0,1,0,0,1]])
print(predict1)
predict1 = mnb.predict([[0,0,1,0,0,1,0,1,0,0,1]])
print(predict1)

[0]
[0]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  "X does not have valid feature names, but"
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:446: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  "X does not have valid feature names, but"


In [21]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred)
precision1 = precision_score(target_test, target_pred1)
recall = recall_score(target_test, target_pred)
recall1 = recall_score(target_test, target_pred1)
print('Precision for GaussianNB: {}'.format(precision))
print('Precision for MultinomialNB: {}'.format(precision1))
print('Recall GaussianNB: {}'.format(recall))
print('Recall MultinomialNB: {}'.format(recall1))

Precision for GaussianNB: 0.5714285714285714
Precision for MultinomialNB: 0.5714285714285714
Recall GaussianNB: 0.5714285714285714
Recall MultinomialNB: 0.5714285714285714


In [22]:
from sklearn import metrics
print("Accuracy for GaussianNB:",metrics.accuracy_score(target_test, target_pred))
print("Accuracy for MultinomialNB:",metrics.accuracy_score(target_test, target_pred1))

Accuracy for GaussianNB: 0.5
Accuracy for MultinomialNB: 0.5
